### ISSUE TITLE
Flash Application - Error Code 19 - Download Failed

### ISSUE THREAD

**Issue by daveabes** [knq/hilink#12]
When attempting to run the updates on the modems, the application is no successfully downloading the programs needed.

Application:
E3372-607_Update_21.11.99.02.00

**Comment by kenshaw** [comment]
This has nothing to do with this package.

**Comment by daveabes** [comment]
Hi thanks for hte update kenshaw, I managed to flash modems. However I needed to use other techniques as the new Huawei modems are locked from being flashed.

For those coming here, you will need to research starting with the needle method and them coming back to this technique.
