### ISSUE TITLE
Confirmed working with Huawei E3372 (Australia)

### ISSUE THREAD

**Issue by geoffreys** [knq/hilink#3]
Not a defect, just a note that this codebase also works with the E3372 running software version 22.315.01.00.74, web UI version 22.315.01.00.74 on Raspberry Pi3.

No other library/module I'd tried worked integrating with this device!  Good luck future google searchers.

**Comment by kenshaw** [comment]
Thanks, appreciate the input.

**Comment by VK2XXY** [comment]
web UI version 22.315.01.00.74   <<<   Is that correct?
