### ISSUE TITLE
InputOffset undefined

### ISSUE THREAD

**Issue by ab1jx** [knq/hilink#4]
I don't know anything about go and probably won't learn.  I installed go version go1.3.3 linux/arm (from Raspbian debs) on one of my Raspberry Pi 3B's for hilink and I get this:

 go get -u github.com/knq/hilink
# github.com/clbanning/mxj
/usr/tmp/gopath/src/github.com/clbanning/mxj/xmlseq.go:308: p.InputOffset   
# undefined (type *xml.Decoder has no field or method InputOffset)

**Comment by kenshaw** [comment]
You need to be running a new version of Go. Go1.3 is 3 years old now -- the call API being used in the `mxj` package wasn't introduced until after Go1.3.
