### ISSUE TITLE
hlcli command line tool not working

### ISSUE THREAD

**Issue by GammaSoul** [knq/hilink#6]
Hi ive intalled this on a Banana Pi M3 but i cant get the hlcli to run....
`go build ./cmd/hinfo/ && ./hinfo`  - works fine and gives me a read out from my stick with the mod firmware installed.
but when i try:
`hlcli help`
i get:
`-bash: hlcli: comand not found`
Sorry am i not doing some thing right? the install procedure of hlcli is very simple.
i have go version 1.8 installed.

**Comment by GammaSoul** [comment]
Hi well i have got it to work by Building it:
`go build github.com/knq/hilink/cmd/hlcli`
Then calling it like so:
`./hlcli help`
So its not puting this into the enviroment path.

**Comment by kenshaw** [comment]
`go build` will only build it in the local directory. You need to use `go install`, which should move the built executable from `$PWD` to `$GOPATH/bin/`. Please make sure that `$GOPATH/bin` is somewhere on your `$PATH`.

**Comment by GammaSoul** [comment]
Ah! right thank you. im on ubuntu 17.10 i had to add the path to /etc/environment.

**Comment by kenshaw** [comment]
I take it you're new to Ubuntu / Linux? You shouldn't add `PATH` to `/etc/environment` as that's a system-wide thing. While you may not have more than one person using the system, it would be advisable to only change it for the local user. If you're using Bash (likely, unless you've changed the default shell), then you can simply do the following to add `$GOPATH/bin` to your `$PATH`: 

```sh
$ echo 'export PATH=$PATH:/path/to/go/bin' >> ~/.bashrc
```
Please note in the above you need to change `/path/to/` to be the correct path where you installed Go. For what it's worth, as I'm guessing you're also new to Go, I would suggest keeping the Go toolchain (ie, the files you downloaded from https://golang.org/dl ) in a separate directory than where you keep your local Go packages -- that is, the directory where `go install` and `go get` write their data. 

For reference, I keep the latest Git source repo at `/usr/local/go` and I keep my local Go packages in `~/go`:

```sh
$ sudo -s
$ cd /usr/local && git clone https://go.googlesource.com/go
```
Note that you will need to build this from source, using an already built Go toolchain. Alternatively, just download the pre-built Go toolchain (from https://golang.org/dl ) and extract that in `/usr/local`: 

```sh
$ sudo -s
$ cd /usr/local && wget https://dl.google.com/go/go1.10.linux-amd64.tar.gz
$ tar -zxvf go1.10.linux-amd64.tar.gz
```

You would then put the following on `$PATH` (ie, edit your `~/.bashrc`):

```sh
$ echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin' >> ~/.bashrc
```
