### ISSUE TITLE
error: hilink error 100003: no power

### ISSUE THREAD

**Issue by FRVisser** [knq/hilink#7]
Hey, 

Really like this library. Keep up the good work.
I know the user part still has to be implemented. I don't have the time to make it, but I did find two use full sources.

https://github.com/HSPDev/Huawei-E5180-API/blob/master/src/HSPDev/HuaweiApi/Router.php#L315

and 

https://github.com/ircykk/huawei-e8272

btw. `no power` could better be translate to `Access denied`

Thanks,
Fokko

**Comment by FRVisser** [comment]
> /*
> 		* Note how the router wants the password to be the following:
> 		* 1) Hashed by SHA256, then the raw output base64 encoded.
> 		* 2) The username is appended with the result of the above, 
> 		*	 AND the current token. Yes, the password changes everytime 
> 		*	 depending on what token we got. This really fucks with scrapers.
> 		* 3) The string from above (point 2) is then hashed by SHA256 again, 
> 		*    and the raw output is once again base64 encoded.
> 		* 
> 		* This is how the router login process works. So the password being sent 
> 		* changes everytime depending on the current user session/token. 
> 		* Not bad actually.
> 		*/

**Comment by chmike** [comment]
Indeed, this package doesn't currently support password authenticated access. 
I see how to add it, because I desperately need it.
