### ISSUE TITLE
Panic error

### ISSUE THREAD

**Issue by chmike** [knq/hilink#9]
I get a panic error when using your hlcli with a Huawei B525S 23a.
Where could I get the documentation to check if the API protocol did change or is different from your ?

hlcli  SignalInfo -endpoint=192.168.8.1 -v
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x12b8f26]

goroutine 1 [running]:
net/http/httputil.DumpResponse(0x0, 0xc42012c101, 0x0, 0x13b58a0, 0xc4200edea0, 0x13b58a0, 0xc4200ede40)
	/usr/local/go/src/net/http/httputil/dump.go:284 +0x46
github.com/knq/hilink.(*httpLogger).RoundTrip(0xc4200edd80, 0xc42012c100, 0xc4200edd80, 0xbed174508d15c166, 0x6fc4b765e)
	/Users/meessen/Sources/go/src/github.com/knq/hilink/opts.go:59 +0xd8
net/http.send(0xc42012c000, 0x13b55e0, 0xc4200edd80, 0xbed174508d15c166, 0x6fc4b765e, 0x1547da0, 0xc42000e9e0, 0xbed174508d15c166, 0xc420055ae8, 0x1)
	/usr/local/go/src/net/http/client.go:252 +0x185
net/http.(*Client).send(0xc420085a70, 0xc42012c000, 0xbed174508d15c166, 0x6fc4b765e, 0x1547da0, 0xc42000e9e0, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).Do(0xc420085a70, 0xc42012c000, 0x24, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:615 +0x28d
github.com/knq/hilink.(*Client).doReq(0xc420094410, 0x137a8d2, 0x18, 0x0, 0x0, 0xc420055d01, 0x0, 0x0, 0x0, 0x0)
	/Users/meessen/Sources/go/src/github.com/knq/hilink/hilink.go:131 +0x116
github.com/knq/hilink.(*Client).NewSessionAndTokenID(0xc420094410, 0x0, 0x0, 0xc420126401, 0x2, 0x8, 0x12c06ad)
	/Users/meessen/Sources/go/src/github.com/knq/hilink/hilink.go:242 +0x62
github.com/knq/hilink.NewClient(0xc420126410, 0x2, 0x2, 0x1, 0x2, 0xc420126410)
	/Users/meessen/Sources/go/src/github.com/knq/hilink/hilink.go:76 +0x157
main.main()
	/Users/meessen/Sources/go/src/github.com/knq/hilink/cmd/hlcli/main.go:210 +0x7d4

**Comment by kenshaw** [comment]
The `verbose` setting is bad. The problem here is that you need to pass the `-endpoint=` with the full URL: `-endpoint=http://<IP>/`. If you're using the default IP (ie, 192.168.8.1) you don't need to specify the endpoint.

**Comment by chmike** [comment]
Thank you for answering so quick. Unfortunately the ˋhlcli SignalInfo ˋ doesn't work. 
This is what I get
```
$ hlcli SignalInfo
error: invalid response
```

**Comment by kenshaw** [comment]
No idea if it works at all or if it ever did. Those commands were written based on possibly bad documentation. Update the code base and try again with `-v`, I fixed the error handling so it shouldn't panic.

**Comment by chmike** [comment]
Here is the output I get with -v:
```
$ hlcli  SignalInfo -v
2018/08/04 10:27:12 GET /api/webserver/SesTokInfo HTTP/1.1
Host: 192.168.8.1
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

2018/08/04 10:27:12 HTTP/1.1 200 OK
Content-Length: 257
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: Keep-Alive
Content-Security-Policy: default-src 'self' 'unsafe-inline' 'unsafe-eval'
Content-Type: text/html
Date: Sat, 04 Aug 2018 10:27:05 GMT
Pragma: no-cache
Set-Cookie: SessionID=mMRLfUNAHcgrpMiHPk2E6fqd20LwO8xiQZ3UGKRPM0eJ56MZMpspJCdpgtiZbPwRy8QCOVGUMVD37A5Zn0YhBq904uanKfIRejhXA1V43rQmYTQmFbrS9KnNED9XYkaA; path=/; HttpOnly;
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?><response><TokInfo>9vETkx2x1nkxFwBFM9DzhB101w4adUtF</TokInfo><SesInfo>mMRLfUNAHcgrpMiHPk2E6fqd20LwO8xiQZ3UGKRPM0eJ56MZMpspJCdpgtiZbPwRy8QCOVGUMVD37A5Zn0YhBq904uanKfIRejhXA1V43rQmYTQmFbrS9KnNED9XYkaA</SesInfo></response>
error: invalid response
```

**Comment by kenshaw** [comment]
The API changed, slightly:

```sh
$ hlcli SignalInfo -v -endpoint='http://192.168.16.1'
2018/08/04 15:37:56 GET /api/webserver/SesTokInfo HTTP/1.1
Host: 192.168.16.1
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

2018/08/04 15:37:56 HTTP/1.1 200 OK
Connection: close
Content-Length: 277
Cache-Control: no-cache
Content-Type: text/html
Date: Thu, 01 Jan 1970 00:00:00 GMT
Server: mini_httpd/1.19 19dec2003
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<response>
<SesInfo>SessionID=oeimsMrMbs+Oku4wTbGQEqPu8MnQkoRbuxIpZbBUB2oQSKFVxFuXILgFN1JjXp39nrSeSQxFOIwsJDYdK6XMRhYAuRjFtdFJzg8GxKVpMFiajUVp5TWxahY/7XHNkcox</SesInfo>
<TokInfo>k1Qqg/StKjrcNADJsjIWczls/YZU3DeC</TokInfo>
</response>
2018/08/04 15:37:56 GET /api/device/signal HTTP/1.1
Host: 192.168.16.1
User-Agent: Go-http-client/1.1
Cookie: SessionID=oeimsMrMbs+Oku4wTbGQEqPu8MnQkoRbuxIpZbBUB2oQSKFVxFuXILgFN1JjXp39nrSeSQxFOIwsJDYdK6XMRhYAuRjFtdFJzg8GxKVpMFiajUVp5TWxahY/7XHNkcox
Accept-Encoding: gzip

2018/08/04 15:37:56 HTTP/1.1 200 OK
Connection: close
Content-Length: 246
Cache-Control: no-cache
Content-Type: text/html
Date: Thu, 01 Jan 1970 00:00:00 GMT
Server: mini_httpd/1.19 19dec2003
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-Download-Options: noopen
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<response>
<pci>250</pci>
<sc></sc>
<cell_id>34102027</cell_id>
<rsrq>-9dB</rsrq>
<rsrp>-85dBm</rsrp>
<rssi>-61dBm</rssi>
<sinr>2dB</sinr>
<rscp></rscp>
<ecio></ecio>
<mode>7</mode>
</response>
{
  "cell_id": "34102027",
  "ecio": "",
  "mode": "7",
  "pci": "250",
  "rscp": "",
  "rsrp": "-85dBm",
  "rsrq": "-9dB",
  "rssi": "-61dBm",
  "sc": "",
  "sinr": "2dB"
}
```
I'll change this to detect when the server is sending the cookie too.

**Comment by chmike** [comment]
I need to have a continuously updating SignalInfo to adjust an external antenna. 
From your output it seam that we need to do the call with the returned session id to get the result back. Do you think we need to get the session id at every call or just once, if the time interval between to calls is small ?

**Comment by kenshaw** [comment]
What is needed is that the session token needs to be read from the cookie (ie the `Set-Cookie` header). The hilink firmware on the modems I'm using return it as part of the XML, as you can see between the differences between what you sent and the output I copied above.

**Comment by chmike** [comment]
It looks like the first transaction sends the session id in the response. The token is to be hashed with the password when we need a logged in session. I looked at some php code doing this (https://github.com/HSPDev/Huawei-E5180-API). 

Apparently there is no set cookie from the router. I suspect that the protocol is that the first time the API is called, we get back a response with the session id and token. We have to call it a second time with the session id as cookie. There is another field referenced in the PHP code, but it isn't apparently required from your output sample.
